services:
  db:
    image: postgres:15-alpine
    container_name: studyplanner-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: studyplanner
      POSTGRES_HOST_AUTH_METHOD: trust  # <--- MUDANÇA 1: Aceita conexão sem frescura
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_new:/var/lib/postgresql/data # <--- MUDANÇA 2: Nome novo para forçar limpeza

  api:
    build: ./backend
    container_name: studyplanner-api
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      JAVA_TOOL_OPTIONS: "-XX:TieredStopAtLevel=1"

  web:
    build: ./frontend
    container_name: studyplanner-web
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - api

volumes:
  postgres_data_new: # <--- MUDANÇA 3: Criando o volume novo