name: Backend CI (Java & Spring Boot)

on:
  push:
    branches: [ "main", "master" ]
    paths:
      - 'backend/**' # Só roda se mexer na pasta backend
  pull_request:
    branches: [ "main", "master" ]
    paths:
      - 'backend/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend # IMPORTANTE: Ajuste se o nome da pasta for diferente

    steps:
    - name: Baixar código (Checkout)
      uses: actions/checkout@v4

    - name: Configurar Java 25
      uses: actions/setup-java@v4
      with:
        java-version: '25'
        distribution: 'temurin'
        cache: maven

    - name: Dar permissão de execução ao Maven Wrapper
      run: chmod +x mvnw

    - name: Rodar Testes
      run: ./mvnw test

    - name: Build (Opcional - verifica se compila tudo)
      run: ./mvnw clean package -DskipTests # Pula testes aqui pq já rodou em cima